# Generated by Django 4.1.5 on 2023-01-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_only_data',
            name='version_date',
            field=models.CharField(max_length=100, verbose_name='交易日期'),
        ),
    ]
