# Generated by Django 4.1.5 on 2023-01-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldApp', '0002_alter_gold_only_data_version_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_data',
            name='version_date',
            field=models.CharField(max_length=100, verbose_name='涨幅'),
        ),
    ]
