# Generated by Django 3.2.16 on 2023-01-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cctv_china_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视国内新闻',
                'verbose_name_plural': '央视国内新闻',
                'db_table': 'tbl_d_news_cctv_china',
            },
        ),
        migrations.CreateModel(
            name='cctv_economy_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视经济新闻',
                'verbose_name_plural': '央视经济新闻',
                'db_table': 'tbl_d_news_cctv_economy',
            },
        ),
        migrations.CreateModel(
            name='cctv_union_news',
            fields=[
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
                ('unique_key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='主键')),
            ],
            options={
                'verbose_name': '央视新闻合并',
                'verbose_name_plural': '央视新闻合并',
                'db_table': 'tbl_d_news_cctv_union_all',
            },
        ),
        migrations.CreateModel(
            name='cctv_world_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视国际新闻',
                'verbose_name_plural': '央视国际新闻',
                'db_table': 'tbl_d_news_cctv_world',
            },
        ),
    ]
