# Generated by Django 2.1.8 on 2023-01-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gold_close_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('year_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='年份')),
                ('min_close', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低收盘价')),
                ('min_close_version_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低收盘价日期')),
                ('min_close_month', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低收盘价月份')),
                ('max_close', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高收盘价')),
                ('max_close_version_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高收盘价日期')),
                ('max_close_month', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高收盘价月份')),
            ],
            options={
                'verbose_name': '黄金收盘价',
                'verbose_name_plural': '黄金收盘价',
                'db_table': 'tbl_d_au_td_close',
            },
        ),
        migrations.CreateModel(
            name='gold_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('open', models.CharField(blank=True, max_length=100, null=True, verbose_name='开盘价')),
                ('high', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高价')),
                ('low', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低价')),
                ('close', models.CharField(blank=True, max_length=100, null=True, verbose_name='收盘价')),
                ('up_or_down', models.CharField(blank=True, max_length=100, null=True, verbose_name='涨幅')),
                ('version_date', models.BigIntegerField(verbose_name='涨幅')),
            ],
            options={
                'verbose_name': '贵金属价格',
                'verbose_name_plural': '贵金属价格',
                'db_table': 'temp_gold_data',
            },
        ),
        migrations.CreateModel(
            name='gold_earning_rate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('year_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='年份')),
                ('max_earning_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='最大收益率')),
                ('average_earning_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='平均收益率')),
            ],
            options={
                'verbose_name': '黄金收益率',
                'verbose_name_plural': '黄金收益率',
                'db_table': 'tbl_d_au_td_earning_rate',
            },
        ),
        migrations.CreateModel(
            name='gold_monthly_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('month_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='月份')),
                ('current_sum_mapping', models.CharField(blank=True, max_length=100, null=True, verbose_name='当月净值')),
                ('history_average_mapping', models.CharField(blank=True, max_length=100, null=True, verbose_name='历史年平均净值')),
                ('history_sum_mapping', models.CharField(blank=True, max_length=100, null=True, verbose_name='历史年净值')),
            ],
            options={
                'verbose_name': '黄金月价格',
                'verbose_name_plural': '黄金月价格',
                'db_table': 'tbl_m_au_td_gold_data_mapping',
            },
        ),
        migrations.CreateModel(
            name='gold_only_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('open', models.CharField(blank=True, max_length=100, null=True, verbose_name='开盘价')),
                ('high', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高价')),
                ('low', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低价')),
                ('close', models.CharField(blank=True, max_length=100, null=True, verbose_name='收盘价')),
                ('up_or_down', models.CharField(blank=True, max_length=100, null=True, verbose_name='涨幅')),
                ('version_date', models.BigIntegerField(verbose_name='交易日期')),
                ('mapping', models.CharField(blank=True, max_length=15, null=True, verbose_name='映射')),
                ('date_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='年月日')),
                ('year_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='年份')),
                ('month_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='月份')),
                ('day_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='日')),
                ('refresh_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='日')),
            ],
            options={
                'verbose_name': '黄金价格',
                'verbose_name_plural': '黄金价格',
                'db_table': 'tbl_au_td_gold_data_analysis',
            },
        ),
        migrations.CreateModel(
            name='gold_yearly_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('year_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='年份')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='净值')),
            ],
            options={
                'verbose_name': '黄金年价格',
                'verbose_name_plural': '黄金年价格',
                'db_table': 'tbl_y_au_td_gold_data_analysis',
            },
        ),
    ]
